name: Freeze PR dependency changes

on:
  pull_request:
    branches:
      - master

jobs:
  freeze-pr-dep-changes:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    uses: FasterSpeeding/Piped/.github/workflows/freeze-for-pr.yml@45039ff4ec17015d4963e6cc9e1c6d7a21add80a
    secrets: inherit
